### ISSUE TITLE
Elicitação de Requisitos - Equipe 1

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#1]
**Descrição**
O trio deverá realizar técnicas de requisitos. 

**Tasks**
 * [x] Buscar requisitos esperados com 3 entrevistas e mapa mental.
 * [x] Buscar requisitos surpresa com Brainstorm.
 * [x] Analisar 2 redes sociais diferentes (Benchmarking) a fim de obter requisitos óbvios.

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Colocar o documento em Markdown

**Comment by lbrunofidelis** [comment]
@lucasmidlhey @Caiocbeleza @lucasqmc quais os apps utilizados no Benchmarking dessa equipe? 
Verifiquem os apps utilizados pelas outras equipes nas issues #12 e #2 para não repetirmos.

**Comment by Caiocbeleza** [comment]
Utilizamos os seguintes:
https://play.google.com/store/apps/details?id=com.badoo.mobile Badoo
https://play.google.com/store/apps/details?id=com.tinder Tinder

**Comment by lbrunofidelis** [comment]
Observações: 
* Tema principal faltante no Brainstorming

Os requisitos foram levantados e o documento está disponível no drive.

**Comment by lbrunofidelis** [comment]
Correções já feitas e analisadas. Fechando a issue.
