### ISSUE TITLE
Rich Picture

### ISSUE THREAD

**Issue by lbrunofidelis** [UnBPaquera/Wiki#10]
**Descrição**
Cada membro deve criar um Rich Picture sobre o tema do projeto e colocar no Drive.

**Tasks**
 * [x] Rich Picture - Daniel Sousa
 * [ ] Rich Picture - Lucas Leite
 * [ ] Rich Picture - Lucas Medeiros
 * [x] Rich Picture - Luis Bruno
 * [ ] Rich Picture - Pedro Miranda
 * [ ] Rich Picture - Ramon Sales
 * [ ] Rich Picture - Tiago Miguel
 * [ ] Rich Picture - Cauê Mateus
 * [x] Rich Picture - Caio César
 * [x] Rich Picture - Lucas Midlhey

**Critérios de Aceitação**
 * [ ] Alta qualidade e legível

**Comment by dansousamelo** [comment]
Acho que seria uma boa fazermos não apenas um rich picture e sim vários, como, um fluxo geral, um fluxo de cadastro, assim como um fluxo analisando os concorrentes da aplicação.

**Comment by dansousamelo** [comment]
Rich Picture Geral

![Rich_Picture](https://user-images.githubusercontent.com/48137972/76795109-2bc8ca00-67a7-11ea-82a3-e29976f9cad1.jpg)

**Comment by lucasmidlhey** [comment]
Rich-Picture geral 

![WhatsApp Image 2020-03-19 at 10 26 54](https://user-images.githubusercontent.com/13874497/77072382-5ba4e700-69cc-11ea-8769-ba4842c598ac.jpeg)

**Comment by lucasmidlhey** [comment]
Vamos fazer os rich picture de fluxo e telas em equipes? assim fica mais facil elicitar os requisitos para essa semana

**Comment by dansousamelo** [comment]
Pra elaborar as telas só na parte de prototipação, primeiro a gente tem que definir o escopo do projeto, consolidar bem as ideias, o outro rich picture, muito importante, seria o das combinações, hj devo terminar um que pensei

**Comment by dansousamelo** [comment]
![WhatsApp Image 2020-03-19 at 16 13 56](https://user-images.githubusercontent.com/48137972/77106185-75125700-69fd-11ea-83f3-879ac02587e7.jpeg)

**Comment by dansousamelo** [comment]
![WhatsApp Image 2020-03-19 at 16 14 04](https://user-images.githubusercontent.com/48137972/77106232-8491a000-69fd-11ea-8577-edf7622fe8aa.jpeg)

**Comment by Caiocbeleza** [comment]
Rich picture geral. Achei q poderia ter uma funcionalidade q faz o que já fazem no perfil do instagram, q é a de vc postar uma foto ou descrição da pessoa q vc quer encontrar, q pode ser anonimamente ou não.

![RichPicture](https://user-images.githubusercontent.com/37124720/77106820-7b550300-69fe-11ea-8782-1182fabcd727.png)

**Comment by lbrunofidelis** [comment]
Rich Picture Geral

![Rich picture](https://user-images.githubusercontent.com/21300624/77107402-675dd100-69ff-11ea-85e6-33cde8fd5abd.jpg)

**Comment by lbrunofidelis** [comment]
Rich Pictures faltantes:
@lucasqmc @medeiroslucas  @pedroMiranda7410 @ramonsales @tmcstiago @caue96 

Issue adicionada com dívida técnica para Sprint 01

**Comment by pedroMiranda7410** [comment]
Minha V1 do Rich Picture que tinha feito antes de começarmos as sprints
<img width="642" alt="Captura de Tela 2020-04-16 às 23 19 24" src="https://user-images.githubusercontent.com/42544693/79525269-d9462c00-8038-11ea-8dba-d367f548497d.png">

**Comment by lbrunofidelis** [comment]
Requisitos baseados nos Rich pictures já levantados, próximos passos definidos na versão 2 do Rich picture no #33 .
