### ISSUE TITLE
Elicitação de Requisitos - Equipe 3

### ISSUE THREAD

**Issue by lbrunofidelis** [UnBPaquera/Wiki#12]
**Descrição**
O trio deverá realizar técnicas de requisitos. 

**Tasks**
 * [x] Buscar requisitos esperados com 3 entrevistas e observações.
 * [x] Buscar requisitos surpresa com Brainstorm.
 * [x] Analisar 2 redes sociais diferentes (Benchmarking) a fim de obter requisitos óbvios.

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Colocar o documento em Markdown

**Comment by lbrunofidelis** [comment]
@dansousamelo documenta aqui quais as redes essa equipe está usando p/ levantar os requisitos óbvios

**Comment by dansousamelo** [comment]
Esses 2:
https://play.google.com/store/apps/details?id=com.evermatch W -Match

https://play.google.com/store/apps/details?id=com.evermatch Namoro Para um Relacionamento Sério

**Comment by lbrunofidelis** [comment]
Documento no Drive revisado.
