### ISSUE TITLE
Análise de Requisitos - Metas de Usabilidade

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#16]
**Descrição**
Desenvolver o processo Análise de Requisitos - Metas de Usabilidade referente a conceitos de Interação Humano Computador.

**Tasks**
 * [ ] Perfil do Usuário  - Daniel
 * [ ] Análise de Tarefas - Luís
 * [ ] Características da Plataforma - Lucas
 * [ ] Princípios Gerais Projeto - Cauê

**Critérios de Aceitação**
 * [ ] Adicionar Referência
 * [ ] Adicionar na Wiki

**Comment by lucasmidlhey** [comment]
Finalizei as caracteristicas da plataforma analisando as elicitações ja feita anteriormente, se alguem puder revisar e me dar um feedback.

**Comment by pedroMiranda7410** [comment]
Ow, tava olhando minhas tarefas e queria saber por que to linkado nessa issue?

**Comment by lbrunofidelis** [comment]
Foi um engano, @pedroMiranda7410. Tô removendo aqui
