### ISSUE TITLE
Elicitação de Requisitos - Equipe 2

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#2]
**Descrição**
O trio deverá realizar técnicas de requisitos. 

**Tasks**
 * [x] Buscar requisitos esperados com 3 entrevistas e observação
 * [x] Buscar requisitos surpresa com Brainstorm.
 * [x] Analisar 2 redes sociais diferentes (Benchmarking) a fim de obter requisitos óbvios.

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Colocar o documento em Markdown

**Comment by lbrunofidelis** [comment]
App utilizados pela equipe no Benchmarking:
https://play.google.com/store/apps/details?id=com.ftw_and_co.happn - Happn
https://play.google.com/store/apps/details?id=com.pinkapp - Lovely

**Comment by lbrunofidelis** [comment]
Falta Brainstorm e Benchmarking, entrando como dívida técnica p/ Sprint 1
