### ISSUE TITLE
Análise do Questionário

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#23]
**Descrição**
Produzir um documento sobre o artefato Questionário.

**Tasks**
 * [x] Analisar Resposta das perguntas fechadas
 * [x] Analisar Resposta das perguntas abertas

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Adicionar na Wiki

**Comment by lbrunofidelis** [comment]
Documento e planilha adicional feita.
