### ISSUE TITLE
Pesquisa sobre gostos - Personalidade

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#25]
**Descrição**
Pesquisar sobre personalidade, procurar artigos, fontes confiáveis para saber o que perguntar ao usuário na criação de um formulário.

**Tasks**
 * [x] Produzir documento sobre
 * [ ] Elaborar as perguntas que serão feitas sobre personalidade

**Critérios de Aceitação**
 * [ ] Adicionar Referência
 * [ ] Adicionar na Wiki
