### ISSUE TITLE
Pesquisa sobre gostos - Música

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#26]
**Descrição**
Pesquisar sobre música, procurar artigos, fontes confiáveis para saber o que perguntar ao usuário na criação de um formulário.

**Tasks**
 * [x] Produzir documento sobre
 * [x] Elaborar as perguntas que serão feitas sobre música.

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Adicionar na Wiki

**Comment by lbrunofidelis** [comment]
Dívida técnica para sprint 3

**Comment by lbrunofidelis** [comment]
@dansousamelo faz o review dessa issue e fecha, caso esteja tudo ok?

**Comment by dansousamelo** [comment]
Tudo certo!
