### ISSUE TITLE
Pesquisa sobre gostos - Hobbies

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#27]
**Descrição**
Pesquisar a sobre Hobbies, procurar artigos, fontes confiáveis para saber o que perguntar ao usuário na criação de um formulário.

**Tasks**
 * [x] Produzir documento sobre
 * [x] Elaborar as perguntas que serão feitas sobre hobbies.

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [ ] Adicionar na Wiki

**Comment by dansousamelo** [comment]
Colocar na wiki está problemático pois deve ser elaborado um documento único.

**Comment by lbrunofidelis** [comment]
Criei o documento, pode adicionar sua parte lá.
Fechando a issue
