### ISSUE TITLE
Pesquisa sobre gostos - Religião

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#28]
**Descrição**
Pesquisar a respeito de Religião procurar artigos, fontes confiáveis para saber o que perguntar ao usuário na criação de um formulário.

**Tasks**
 * [ ] Produzir documento sobre
 * [ ] Elaborar as perguntas que serão feitas sobre religião.

**Critérios de Aceitação**
 * [ ] Adicionar Referência
 * [ ] Adicionar na Wiki

**Comment by dansousamelo** [comment]
Pesquisa concluída.
