### ISSUE TITLE
Pesquisa sobre gostos - Culinária

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#29]
**Descrição**
Pesquisar a respeito de culinária, procurar artigos, fontes confiáveis para saber o que perguntar ao usuário na criação de um formulário.

**Tasks**
 * [ ] Produzir documento sobre
 * [ ] Elaborar as perguntas que serão feitas sobre culinária

**Critérios de Aceitação**
 * [ ] Adicionar Referência
 * [ ] Adicionar na Wiki

**Comment by lbrunofidelis** [comment]
Analizado e finalizado.
Fechando a issue.
