### ISSUE TITLE
Pesquisa sobre gostos - Política

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#30]
**Descrição**
Pesquisar a respeito de política, procurar artigos, fontes confiáveis para saber o que perguntar ao usuário na criação de um formulário.

**Tasks**
 * [x] Produzir documento sobre
 * [x] Elaborar as perguntas que serão feitas sobre política.

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Adicionar na Wiki

**Comment by dansousamelo** [comment]
Adicionado a pesquisa geral sobre gostos.
