### ISSUE TITLE
Ajustes no Github

### ISSUE THREAD

**Issue by lbrunofidelis** [UnBPaquera/Wiki#42]
**Descrição**
Organização do repositório do Github.

**Tasks**
 * [x] Criação do readme
 * [x] Atualizar a logo
 * [x] Políticas de commits e de branchs
 * [x] Guia de contribuição

**Comment by dansousamelo** [comment]
Dívida técnica da Sprint 4.
