### ISSUE TITLE
Modelagem BPMN

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#45]
**Descrição**
Realizar a modelagem BPMN.

**Tasks**
 * [ ] Modelagem Geral
 * [ ] Elaboração Inicial de Artefatos
 * [ ] Definição de Projeto
 * [ ] Definição de Metodologias e Abordagens
 * [ ] Metodologia de Desenvolvimento
 * [ ] Planejamento da Sprint
 * [ ] Retrospectiva da Sprint
 * [ ] Review da Sprint

**Critérios de Aceitação**
 * [ ] Adicionar Referência
