### ISSUE TITLE
Elaborar Entrevista e Questionário

### ISSUE THREAD

**Issue by dansousamelo** [UnBPaquera/Wiki#6]
**Descrição**
Elaborar as perguntas para fazer entrevistas e um questionário.

**Tasks**
 * [x] Elaborar perguntas da entrevista
 * [x] Elaborar perguntas do questionário

**Critérios de Aceitação**
 * [x] Adicionar Referência
 * [x] Colocar o documento em Markdown

**Comment by dansousamelo** [comment]
Pedimos a Carolina para divulgar o questionário

**Comment by lbrunofidelis** [comment]
Entrevista disponível nos documentos de cada equipe e questionário disponível em:
https://docs.google.com/forms/d/e/1FAIpQLSeMe4pR-FAluv7Nr6OMlcC79Sr3XlxyWfJb3XdMZ682fh3OYg/viewform
